name: Workspace Integration Test

on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        default: main
      config_package:
        type: string
        default: ""
      colcon_build_args:
        type: string
        default: ""
      colcon_test_args:
        type: string
        default: ""
    secrets:
      studio_license_key:
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ inputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
  integration-test-in-studio-container:
    needs: setup
    runs-on: studio_16_core_runner
    env:
      STUDIO_LICENSE_KEY: ${{ secrets.studio_license_key || secrets.STUDIO_CI_LICENSE_KEY }}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /tmp/cyclonedds.xml
      STUDIO_DOCKER_TAG: ${{ inputs.image_tag }}
      # We always need to test in mocked hardware
      STUDIO_CONFIG_PACKAGE: ${{ inputs.config_package }}
    container: picknikciuser/moveit-studio:${{ inputs.image_tag }}
    steps:
      - name: Check if config package specified
        id: check_config_package
        run: |
          if [ -z "${{ inputs.config_package }}" ]; then
            echo "No config package specified, building all packages"
            echo "config_package_test_arg=" >> $GITHUB_OUTPUT
            echo "config_package_build_arg=" >> $GITHUB_OUTPUT
          else
            echo "Using specified config package: ${{ inputs.config_package }}"
            echo "config_package_test_arg=--packages-select ${{ inputs.config_package }}" >> $GITHUB_OUTPUT
            echo "config_package_build_arg=--packages-up-to ${{ inputs.config_package }}" >> $GITHUB_OUTPUT
          fi

      - name: Set USER_WS environment variable
        id: set_user_ws
        run: echo "USER_WS=/__w/$(basename ${{ github.repository }})/$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: License key exists
        run: |
          if [ -z "$STUDIO_LICENSE_KEY" ]; then
            echo "STUDIO_CI_LICENSE_KEY is not set in the repository secrets"
            echo "ERROR: Please set the STUDIO_LICENSE_KEY secret in the repository settings" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      # The 'lo' interfaces will not have multicast, and will fail trying to claim a participant index
      # with the default cyclone dds config. We set one for the unit tests to be able to execute.
      - name: Configure DDS
        run: |
          cat <<EOF > /tmp/cyclonedds.xml
          <?xml version="1.0" ?>
          <CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
           <Domain id="any">
               <General>
                   <Interfaces>
                       <NetworkInterface autodetermine="true"/>
                   </Interfaces>
                   <AllowMulticast>false</AllowMulticast>
               </General>
               <Discovery>
                   <ParticipantIndex>auto</ParticipantIndex>
                   <Peers>
                       <Peer Address="127.0.0.1" />
                   </Peers>
                   <MaxAutoParticipantIndex>50</MaxAutoParticipantIndex>
               </Discovery>
           </Domain>
          </CycloneDDS>
          EOF
      - name: Install colcon mixins
        run: |
          colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          colcon mixin update
          colcon metadata add default https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml
          colcon metadata update
          cp $USER_WS/colcon-defaults.yaml ~/.colcon/defaults.yaml
          echo "Using ~/.colcon/defaults.yaml:"
          cat ~/.colcon/defaults.yaml
      - name: Install rosdeps
        run: |
          . /opt/ros/humble/setup.sh
          . /opt/underlay_ws/install/setup.sh
          . /opt/overlay_ws/install/setup.sh
          apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
      - name: Run colcon build
        run: |
          . /opt/ros/humble/setup.sh
          . /opt/underlay_ws/install/setup.sh
          . /opt/overlay_ws/install/setup.sh
          colcon build ${{ inputs.colcon_build_args }} ${{ steps.check_config_package.outputs.config_package_build_arg }}
      - name: Run colcon test
        run: |
          . /opt/ros/humble/setup.sh
          . /opt/underlay_ws/install/setup.sh
          . /opt/overlay_ws/install/setup.sh
          . ./install/setup.sh
          env
          # Create virtual framebuffer to allow GLFW to render in MuJoCo tests
          unset MUJOCO_GL
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 &
          echo "Running colcon test"
          colcon test --retest-until-pass 1 ${{ inputs.colcon_test_args }} ${{ steps.check_config_package.outputs.config_package_test_arg }}
      - if: always()
        run: |
          colcon test-result --verbose
      # Upload test results as artifacts to be able to see them in the github actions UI
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ inputs.config_package }}
          path: |
            build/*/test_results/
            build/*/Testing/
          retention-days: 15
