name: Workspace Integration Test

on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        default: main
      config_package:
        type: string
        default: ""
      colcon_build_args:
        type: string
        default: ""
      colcon_test_args:
        type: string
        default: ""
      runner:
        type: string
        default: "depot-ubuntu-24.04-16"

    secrets:
      moveit_license_key:
        required: true

jobs:
  integration-test-in-studio-container:
    runs-on: ${{ inputs.runner }}
    strategy:
      matrix:
        ros_distro:
          - humble
    env:
      MOVEIT_LICENSE_KEY: ${{ secrets.moveit_license_key }}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /tmp/cyclonedds.xml
      MOVEIT_DOCKER_TAG: ${{ inputs.image_tag }}-${{ matrix.ros_distro }}
      # We always need to test in mocked hardware
      MOVEIT_CONFIG_PACKAGE: ${{ inputs.config_package }}
    container: picknikciuser/moveit-studio:${{ inputs.image_tag }}-${{ matrix.ros_distro }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check if config package specified
        id: check_config_package
        run: |
          if [ -z "${{ inputs.config_package }}" ]; then
            echo "No config package specified, building all packages"
            echo "config_package_test_arg=" >> $GITHUB_OUTPUT
            echo "config_package_build_arg=" >> $GITHUB_OUTPUT
          else
            echo "Using specified config package: ${{ inputs.config_package }}"
            echo "config_package_test_arg=--packages-select ${{ inputs.config_package }}" >> $GITHUB_OUTPUT
            echo "config_package_build_arg=--packages-up-to ${{ inputs.config_package }}" >> $GITHUB_OUTPUT
          fi

      - name: Set USER_WS environment variable
        id: set_user_ws
        run: echo "USER_WS=/__w/$(basename ${{ github.repository }})/$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - uses: actions/checkout@v6.0.2
        with:
          submodules: recursive
          lfs: true
      # The 'lo' interfaces will not have multicast, and will fail trying to claim a participant index
      # with the default cyclone dds config. We set one for the unit tests to be able to execute.
      - name: Configure DDS
        run: |
          cat <<EOF > /tmp/cyclonedds.xml
          <?xml version="1.0" ?>
          <CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
           <Domain id="any">
               <General>
                   <Interfaces>
                       <NetworkInterface autodetermine="true"/>
                   </Interfaces>
                   <AllowMulticast>false</AllowMulticast>
               </General>
               <Discovery>
                   <ParticipantIndex>auto</ParticipantIndex>
                   <Peers>
                       <Peer Address="127.0.0.1" />
                   </Peers>
                   <MaxAutoParticipantIndex>50</MaxAutoParticipantIndex>
               </Discovery>
           </Domain>
          </CycloneDDS>
          EOF
      - name: Install colcon mixins
        run: |
          colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          colcon mixin update
          colcon metadata add default https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml
          colcon metadata update
          cp $USER_WS/colcon-defaults.yaml ~/.colcon/defaults.yaml
          echo "Using ~/.colcon/defaults.yaml:"
          cat ~/.colcon/defaults.yaml
      - name: Install rosdeps
        run: |
          . /opt/ros/humble/setup.sh
          . /opt/overlay_ws/install/setup.sh
          apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
      - name: Run colcon build
        run: |
          . /opt/ros/humble/setup.sh
          . /opt/overlay_ws/install/setup.sh
          colcon build ${{ inputs.colcon_build_args }} ${{ steps.check_config_package.outputs.config_package_build_arg }}
      - name: Run colcon test
        run: |
          . /opt/ros/humble/setup.sh
          . /opt/overlay_ws/install/setup.sh
          . ./install/setup.sh
          env
          # Create virtual framebuffer to allow GLFW to render in MuJoCo tests
          unset MUJOCO_GL
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 &
          echo "Running colcon test"
          external_packages="$(colcon list --base-paths src/external_dependencies --names-only || true)"
          if [ -n "$external_packages" ]; then
              colcon test --packages-skip $external_packages --retest-until-pass 1 ${{ inputs.colcon_test_args }} ${{ steps.check_config_package.outputs.config_package_test_arg }}
          else
              colcon test --retest-until-pass 1 ${{ inputs.colcon_test_args }} ${{ steps.check_config_package.outputs.config_package_test_arg }}
          fi
      - if: always()
        run: |
          colcon test-result --verbose
      # Upload test results as artifacts to be able to see them in the github actions UI
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ inputs.config_package }}
          path: |
            build/*/test_results/
            build/*/Testing/
          retention-days: 15
